---
title: "Final Projecet"
output: html_notebook
---

```{r}
# clean up workspace environment
rm(list = ls())

# all packages used for the assignment
library(mosaic)
library(tidyverse)
library(DataComputing)
library(xlsx)
```

### Upoad the data
```{r}
library(readxl)
whiteMenEmploymentLevel <- read_excel("Data/whiteMenEmploymentLevel.xlsx", skip=12)
whiteMenUnemploymentLevel <- read_excel("Data/whiteMenUnemploymentLevel.xlsx", skip=12)
white_women_unemployed <- read_excel("Data/white women unemployed.xlsx", skip = 12)
white_women_employed <- read_excel("Data/white women employed.xlsx", skip = 12)
latino_women_unemployed <- read_excel("Data/latino women unemployed.xlsx", skip = 12)
latino_women_employed <- read_excel("Data/latino women employed.xlsx", skip = 12)
latino_men_unemployed <- read_excel("Data/latino men unemployed.xlsx", skip = 12)
latino_men_employed <- read_excel("Data/latino men employed.xlsx", skip = 12)
black_women_unemployed <- read_excel("Data/black women unemployed.xlsx", skip = 12)
black_women_employed <- read_excel("Data/black women employed.xlsx", skip = 12)
black_men_unemployment <- read_excel("Data/black men unemployment.xlsx", skip = 12)
black_men_employment <- read_excel("Data/black men employment.xlsx", skip = 12)
Reasons <- read_excel("Reason data.xlsx")

```

### View the data

```{r}
whiteMenEmploymentLevel
black_men_employment
whiteMenUnemploymentLevel

```
### Create function that can help data wrangling
```{r}
employment<-function(x){       # function that help calculate mean employment 
  x <- 
    x %>% 
    filter(Year != "2019") %>%
  mutate (total= Jan+Feb+Mar+ Apr+May+Jun+Jul+Aug+Sep+Oct+Nov+Dec)%>%
  mutate(Employment_Mean=total/12)%>%
    select(Year,Employment_Mean)
  return(x)
}

unemployment <-function(y){   # function that help calculate mean unemployment
  y <- 
    y %>% 
    filter(Year != "2019") %>%
  mutate (total= Jan+Feb+Mar+ Apr+May+Jun+Jul+Aug+Sep+Oct+Nov+Dec)%>%
  mutate(UnEmployment_Mean=total/12)%>%
    select(Year,UnEmployment_Mean)
  return(y)
}


```

### Find out mean employment and unemployment
```{r}
whiteMenEmploymentLevel<-
  employment(whiteMenEmploymentLevel)%>%
  mutate(Race="White") %>%
  mutate(Sex="Men")
  whiteMenEmploymentLevel

```

```{r}
whiteMenUnemploymentLevel<-
unemployment(whiteMenUnemploymentLevel)%>%
  mutate(Race="White") %>%
  mutate(Sex="Men")
whiteMenUnemploymentLevel
```

```{r}
white_women_employed<-
employment(white_women_employed)%>%
  mutate(Race="White") %>%
  mutate(Sex="Women")
white_women_employed


```

```{r}
white_women_unemployed<-
unemployment(white_women_unemployed)%>%
  mutate(Race="White") %>%
  mutate(Sex="Women")
white_women_unemployed
```

```{r}
latino_men_employed<-
employment(latino_men_employed)%>%
  mutate(Race="Latino") %>%
  mutate(Sex="Men")
latino_men_employed
```

```{r}
latino_men_unemployed<-
unemployment(latino_men_unemployed)%>%
  mutate(Race="Latino") %>%
  mutate(Sex="Men")
latino_men_unemployed
```


```{r}
latino_women_employed<-
employment(latino_women_employed)%>%
  mutate(Race="Latino") %>%
  mutate(Sex="Women")
latino_women_employed
```

```{r}
latino_women_unemployed<-
unemployment(latino_women_unemployed)%>%
  mutate(Race="Latino") %>%
  mutate(Sex="Women")
latino_women_unemployed
```

```{r}
black_men_employment<-
employment(black_men_employment)%>%
  mutate(Race="African American") %>%
  mutate(Sex="Men")
black_men_employment
```


```{r}
black_men_unemployment<-
unemployment(black_men_unemployment)%>%
  mutate(Race="African American") %>%
  mutate(Sex="Men")
black_men_unemployment
```

```{r}
black_women_employed<-
employment(black_women_employed)%>%
  mutate(Race="African American") %>%
  mutate(Sex="Women")
black_women_employed
```


```{r}
black_women_unemployed<-
unemployment(black_women_unemployed)%>%
  mutate(Race="African American") %>%
  mutate(Sex="Women")
black_women_unemployed
```

### join table for each race and sex
```{r}
WhiteMen<-
  whiteMenEmploymentLevel %>%
  left_join(whiteMenUnemploymentLevel)
WhiteMen
```


```{r}
WhiteWomen<-
  white_women_employed %>%
  left_join(white_women_unemployed)
WhiteWomen
```

```{r}
LatinoMen<-
  latino_men_employed%>%
  left_join(latino_men_unemployed)
LatinoMen
```

```{r}
LatinoWomen<-
  latino_women_employed %>%
  left_join(latino_women_unemployed)
LatinoWomen
```
```{r}
BlackMen<-
  black_men_employment %>%
  left_join(black_men_unemployment)
BlackMen
```
```{r}
BlackWomen<-
  black_women_employed %>%
  left_join(black_women_unemployed)
BlackWomen
```

### join table into one
```{r}
UnemploymentRate<-
  rbind(WhiteMen,WhiteWomen,LatinoMen,LatinoWomen,BlackMen,BlackWomen)
UnemploymentRate
```

### calculate Unempolyment rate
```{r}
UnemploymentRate1<-
UnemploymentRate %>%
  mutate(Unemployment_Rate=UnEmployment_Mean/(UnEmployment_Mean+Employment_Mean))%>%
  select(Year, Race,Sex,Unemployment_Rate) %>%
  mutate(Year= as.character(Year))
UnemploymentRate1


```

### Graph of unemployment rate for different sex and race
```{r fig.width=10}
UnemploymentRate1%>%
  ggplot(aes(x=Year, y= Unemployment_Rate, colour = Race))+
  geom_point()+
  facet_wrap(~ Sex)

```

```{r}
UnemploymentRate1%>%
  ggplot(aes(x=Race, y= Unemployment_Rate,color=Race))+
  geom_boxplot()+
  geom_point()
  facet_wrap(~ Sex)

```


###
```{r}
UnemploymentRate2<-
UnemploymentRate1%>%
  group_by(Year)%>%
  summarise(mean_rate = mean(Unemployment_Rate))
 
UnemploymentRate2$Year[which(UnemploymentRate2$mean_rate==max(UnemploymentRate2$mean_rate))]



```

###
```{r}
Reasons

Reasons <-
  Reasons%>%
  filter(Reason %in% c("Job losers and persons who completed temporary jobs","Job leavers","Reentrants","New entrants"))%>%
  rename(Latino = Hispanic)
Reasons
```

###
```{r}
UnemploymentRate3 <-
UnemploymentRate%>%
  filter(Year =="2010")%>%
  mutate(labor = Employment_Mean+UnEmployment_Mean)%>%
  group_by(Race)%>%
  summarise(total = sum(labor))
UnemploymentRate3
```
###
```{r}
Reasons <-
  Reasons%>%
gather(key = Race, value = number, White, `African American`, Latino)%>%
  left_join(UnemploymentRate3, by = c("Race"="Race"))%>%
  mutate(rate = number/total)%>%
  select(Reason, Race, rate)
Reasons
```

```{r fig.height=15, fig.width=15}
Reasons %>%
  ggplot(aes(x=Reason,y=rate,fill=Race))+
  geom_col()+
  facet_grid(Race~.)
```









